### ISSUE TITLE
Null pointer dereference in `forwarders.Forward`

### ISSUE THREAD

**Issue by mflendrich** [Kong/gateway-operator#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I tried to follow `README.md` instructions to deploy the operator and came across a SIGSEGV crash:

```console
$ kubectl kustomize https://github.com/Kong/kubernetes-ingress-controller/config/crd | kubectl apply -f -
$ kubectl kustomize https://github.com/kubernetes-sigs/gateway-api/config/crd | kubectl apply -f -
$ kubectl kustomize https://github.com/kong/gateway-operator/config/default | kubectl apply -f -
$ # wait
$ kubectl logs pod/gateway-operator-controller-manager-79d77768b5-4d7vr -n kong-system
{"level":"info","ts":1661254855.123566,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":"127.0.0.1:8080"}
{"level":"info","ts":1661254855.1248488,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate"}
{"level":"info","ts":1661254855.1249127,"logger":"setup","msg":"start webhook server","listen_address":":9443"}
{"level":"info","ts":1661254855.1249454,"logger":"setup","msg":"starting anonymous reports"}
W0823 11:40:55.125102       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"level":"info","ts":1661254855.197499,"logger":"setup","msg":"starting telemetry manager"}
{"level":"info","ts":1661254855.197544,"logger":"setup","msg":"starting manager"}
{"level":"info","ts":1661254855.1977184,"msg":"Starting server","kind":"health probe","addr":"[::]:8081"}
{"level":"info","ts":1661254855.197718,"msg":"Starting server","path":"/metrics","kind":"metrics","addr":"127.0.0.1:8080"}
{"level":"info","ts":1661254855.1977065,"logger":"controller-runtime.webhook.webhooks","msg":"Starting webhook server"}
I0823 11:40:55.197790       1 leaderelection.go:248] attempting to acquire leader lease kong-system/a7feedc84.konghq.com...
{"level":"info","ts":1661254855.197934,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":1661254855.198004,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
{"level":"info","ts":1661254855.1979928,"logger":"controller-runtime.webhook","msg":"Serving webhook server","host":"","port":9443}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x15d909e]

goroutine 234 [running]:
github.com/kong/kubernetes-telemetry/pkg/forwarders.(*tlsForwarder).Forward(0x0, {0x1c71e70?, 0xc000642280?}, {0xc000272240, 0x117, 0x120})
	/go/pkg/mod/github.com/kong/kubernetes-telemetry@v0.0.0-20220819082419-d27dcce6d46c/pkg/forwarders/tlsforwarder.go:66 +0x5e
github.com/kong/kubernetes-telemetry/pkg/telemetry.NewConsumer.func1()
	/go/pkg/mod/github.com/kong/kubernetes-telemetry@v0.0.0-20220819082419-d27dcce6d46c/pkg/telemetry/consumer.go:49 +0x1c3
created by github.com/kong/kubernetes-telemetry/pkg/telemetry.NewConsumer
	/go/pkg/mod/github.com/kong/kubernetes-telemetry@v0.0.0-20220819082419-d27dcce6d46c/pkg/telemetry/consumer.go:35 +0x171

```

### Expected Behavior

No segfault on operator startup :smile_cat: 

### Kong Ingress Controller version

```shell
Operator efea71c1b334f4eb5d9be0e845127f54a2600834
KIC n/a
```

### Kubernetes version

```shell
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-18T02:29:34Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24+", GitVersion:"v1.24.3-2+63243a96d1c393", GitCommit:"63243a96d1c3932c704cf0625f5834411bc3b2e6", GitTreeState:"clean", BuildDate:"2022-07-19T17:57:14Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by mflendrich** [comment]
Root cause analysis:

1. I ran this on `microk8s` and I forgot to enable the `dns` addon.
2. This caused `NewTLSForwarder` https://github.com/Kong/kubernetes-telemetry/blob/d27dcce6d46c05f8cb139275c6abf3e20e1ffce0/pkg/forwarders/tlsforwarder.go#L32 to fail with silent error and return `nil`.
3. The `nil` was passed to `NewConsumer` which spawned a goroutine where the eventual nil dereference happened.

After I ran `microk8s enable dns`, KGO starts up just fine. The failure mode in case of DNS unavailability doesn't look right, though :trollface:.

**Comment by pmalek** [comment]
https://github.com/Kong/kubernetes-telemetry/pull/60 should fix it, i.e. report the error.
